### ISSUE TITLE
Get 403 Response when using scroll option

### ISSUE THREAD

**Issue by ChenZiHong-Gavin** [te-papa/collections-api#10]
I made the request the same as the tutorial, but get a 403 code and response: {"message":"Forbidden"}

**Comment by lucyschrader** [comment]
We've just realised that you need to turn off redirects for the request. The request is seeing the 303 and assuming it should send you elsewhere, but since the API's response doesn't actually redirect you anywhere valid, it's providing a 403 response instead.

I'll add this to the documentation now, and put in a change request to see if this can be made to work more smoothly, or at least fail gracefully.
